function createUuid() {
  const s: string[] = [];
  const uuidData = '0123456789abcdefghijklmnopqrstuvwxyz';
  const uuidDataLength = uuidData.length;
  for (let i = 0; i < 36; i++) {
    s[i] = uuidData.substr(Math.floor(Math.random() * uuidDataLength), 1);
  }
  const uuid = s.join('');
  return uuid;
}

// 表单基础信息
export const basicInfo = [
  {
    label: '设备类型',
    name: 'type',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '设备名称',
    name: 'name',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '设备编号',
    name: 'deviceNumber',
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '设备型号',
    name: 'deviceModel',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '所属站点',
    name: 'substationCode',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '出厂编号',
    name: 'serialNumber',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5]+$/,
    message: '请输入正确的出厂编号',
  },
  {
    label: '出厂日期',
    name: 'productionDate',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
    pattern:
      /^(\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) (0\d|1\d|2[0-3]):([0-5]\d):([0-5]\d))$/,
    message: '请输入正确的出厂日期',
  },
  {
    label: '投运日期',
    name: 'operationDate',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
    pattern:
      /^(\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) (0\d|1\d|2[0-3]):([0-5]\d):([0-5]\d))$/,
    message: '请输入正确的投运日期',
  },
  {
    label: '防护等级',
    name: 'protectionGrade',
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '存储温度(℃)',
    name: 'storageTemperature',
    devicesType: [],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5]+$/g,
    message: '请输入正确的温度',
  },
  {
    label: '重量(kg)',
    name: 'deviceWeight',
    devicesType: [],
    id: createUuid(),
    pattern: /^\d*\.?\d+$/,
    message: `请输入正确的重量`,
  },
  {
    label: '尺寸(cm)',
    name: 'deviceSize',
    devicesType: [],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5a-zA-Z]+$/g,
    message: '请输入正确的尺寸',
  },
  {
    label: '备注',
    name: 'remark',
    devicesType: [],
    htmlLabel: 'textArea',
    id: createUuid(),
  },
];

// SIM卡基础信息
export const SIMBasicInfo = [
  {
    label: '设备类型',
    name: 'type',
    isRequired: true,
    id: createUuid(),
  },
  {
    label: '设备名称',
    name: 'name',
    id: createUuid(),
    isRequired: true,
  },
  {
    label: '卡号',
    name: 'cardNumber',
    isRequired: true,
    pattern: /^[^\u4e00-\u9fa5]+$/,
    id: createUuid(),
    message: '请输入正确的卡号',
  },
  {
    label: '运营商',
    name: 'telOperator',
    isRequired: true,
    id: createUuid(),
  },
  {
    label: '所属站点',
    name: 'substationCode',
    isRequired: true,
    id: createUuid(),
  },
  {
    label: '投运日期',
    name: 'operationDate',
    isRequired: true,
    id: createUuid(),
    pattern:
      /^(\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) (0\d|1\d|2[0-3]):([0-5]\d):([0-5]\d))$/,
    message: '请输入正确的投运日期',
  },
];

// 厂商信息
export const factoryInfo = [
  {
    label: '厂商名称',
    name: 'manufacturer',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '厂商联系人',
    name: 'manufacturerContact',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
  },
  {
    label: '厂商联系方式',
    name: 'manufacturerPhone',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5a-zA-Z]+$/g,
    message: '请输入正确手机号',
  },
  {
    label: '质保有效期',
    name: 'warrantyPeriodDate',
    isRequired: true,
    devicesType: [],
    id: createUuid(),
    pattern:
      /^(\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) (0\d|1\d|2[0-3]):([0-5]\d):([0-5]\d))$/,
    message: '请输入正确的出厂日期',
  },
  {
    label: '合同号',
    name: 'contractNumber',
    devicesType: [],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5]+$/,
    message: '请输入正确的合同号',
  },
];

// 设备参数
export const deviceParams = [
  {
    label: '电池堆数量(堆)',
    name: 'heapAmount',
    isRequired: true,
    devicesType: ['111'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: 'BMS数量(套)',
    name: 'bmsAmount',
    isRequired: true,
    devicesType: ['111'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '标称电压(v)',
    name: 'normalVoltage',
    isRequired: true,
    devicesType: ['112', '104', '200'],
    id: createUuid(),
  },
  {
    label: '工作电压范围(v)',
    name: 'voltageWorkRange',
    isRequired: true,
    devicesType: ['112', '104', '200'],
    id: createUuid(),
  },
  {
    label: '循环次数(次)',
    name: 'cycleLife',
    isRequired: true,
    devicesType: ['112', '104', '200'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的循环次数`,
  },
  {
    label: '标称容量(Ah)',
    name: 'normalCapacityAh',
    isRequired: true,
    devicesType: ['111', '112'],
    id: createUuid(),
  },
  {
    label: '最大持续充电倍率(C)',
    name: 'maxChargeRate',
    isRequired: true,
    devicesType: ['112', '104'],
    id: createUuid(),
  },
  {
    label: '最小持续充电倍率(C)',
    name: 'minChargeRate',
    isRequired: true,
    devicesType: ['112', '104'],
    id: createUuid(),
  },
  {
    label: '电池簇数量(簇)',
    name: 'clusterAmount',
    isRequired: true,
    devicesType: ['112'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '标称能量(kWh)',
    name: 'normalEnergyKwh',
    isRequired: true,
    devicesType: ['111', '112', '104', '200'],
    id: createUuid(),
  },
  {
    label: 'PCS数量(台)',
    name: 'pcsAmount',
    isRequired: true,
    devicesType: ['111'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '消防类型',
    name: 'fireType',
    isRequired: true,
    devicesType: ['111'],
    id: createUuid(),
  },
  {
    label: '额标称容量(Ah)', // TODO: 缺少返回字段
    name: '',
    isRequired: true,
    devicesType: ['104', '200'],
    id: createUuid(),
  },
  {
    label: '电池PACK数量(个)',
    name: 'packAmount',
    isRequired: true,
    devicesType: ['104'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '单体最大充电电压(V)',
    name: 'maxSingleVoltage',
    isRequired: true,
    devicesType: ['200'],
    id: createUuid(),
  },
  {
    label: '单体最小放电电压(V)',
    name: 'minSingleVoltage',
    isRequired: true,
    devicesType: ['200'],
    id: createUuid(),
  },
  {
    label: '电芯数量(个)',
    name: 'batteryAmount',
    isRequired: true,
    devicesType: ['200'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '直流电压范围(v)',
    name: 'dcVoltageRange',
    isRequired: false,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '直流输入最大电流(A)',
    name: 'maxDcInputCurrent',
    isRequired: false,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '额定电网电压(A)',
    name: 'ratedVoltage',
    isRequired: true,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '交流额定电流(A)',
    name: 'ratedCurrent',
    isRequired: true,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '交流额定功率(kW)',
    name: 'ratedPower',
    isRequired: true,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '最大转换效率(%)',
    name: 'maxConversionEfficiency',
    isRequired: true,
    devicesType: ['108'],
    id: createUuid(),
  },
  {
    label: '通讯接口',
    name: 'protocolInterface',
    isRequired: true,
    devicesType: ['108', 'BMS'],
    id: createUuid(),
  },
  {
    label: '通讯规约',
    name: 'protocol',
    isRequired: true,
    devicesType: ['108', 'BMS'],
    id: createUuid(),
  },
  {
    label: '数量',
    name: 'amount',
    isRequired: true,
    devicesType: ['108', 'BMS'],
    id: createUuid(),
    pattern: /^[1-9]\d*$/,
    message: `请输入正确的数量`,
  },
  {
    label: '电流检测范围(A)',
    name: 'currentCheckRange',
    isRequired: true,
    devicesType: ['BMS'],
    id: createUuid(),
  },
  {
    label: '电压检测范围(v)',
    name: 'voltageCheckRange',
    isRequired: true,
    devicesType: ['BMS'],
    id: createUuid(),
  },
  {
    label: '温度检测范围(℃)',
    name: 'temperatureCheckRange',
    isRequired: true,
    devicesType: ['BMS'],
    id: createUuid(),
  },
  {
    label: '额定功率(kW)',
    name: 'ratedOutputPower',
    isRequired: true,
    devicesType: ['27'],
    id: createUuid(),
    pattern: /^\d*\.?\d+$/,
    message: `请输入正确的额定功率`,
  },
  {
    label: '接入容量(kW)',
    name: 'gridConnectionCapacity',
    isRequired: true,
    devicesType: ['27'],
    id: createUuid(),
    pattern: /^\d*\.?\d+$/,
    message: `请输入正确的接入容量`,
  },
  {
    label: '通讯方式',
    name: 'communicationMethod',
    devicesType: ['113'],
    id: createUuid(),
  },
  {
    label: '绑定的SIM卡卡号',
    name: 'bindSimCard',
    isRequired: true,
    devicesType: ['113'],
    id: createUuid(),
    pattern: /^[^\u4e00-\u9fa5]+$/,
    message: `请输入正确的SIM卡卡号`,
  },
  {
    label: '每月流量(MB)',
    name: 'monthDataTraffic',
    devicesType: ['114'],
    id: createUuid(),
    pattern: /^\d*\.?\d+$/,
    message: `请输入正确的每月流量`,
  },
  {
    label: '备注',
    name: 'extendRemark',
    devicesType: ['51'],
    htmlLabel: 'textArea',
    id: createUuid(),
  },
];
